- name: Extract the k8s bits
  unarchive:
    src: "https://{{ s3_server }}/{{ bucket }}/{{ directory }}/{{ build_version }}/{{ item }}"
    dest: "/usr/local/bin/"
    remote_src: yes
    extra_opts:
      - --strip-components=3
  with_items:
    - kubernetes-test-linux-ppc64le.tar.gz
    - kubernetes-client-linux-ppc64le.tar.gz
    - kubernetes-server-linux-ppc64le.tar.gz