---
- name: Install containerd
  yum:
    name:
      - containerd
      - device-mapper-persistent-data
      - lvm2
    state: present
    disable_gpg_check: true

- name: Create a /etc/containerd dir
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Generate /etc/containerd/config.toml
  template:
    src: containerd/config.toml.j2
    dest: /etc/containerd/config.toml
    mode: '0644'

- name: Enable and Restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes
