---
- name: Add Redhat Subscription
  block:
    - name: check username and password are set
      fail:
        msg: "username and password are the mandatory values to execute the playbook for rhel"
      when:  ansible_distribution == "RedHat" and  username is not defined or password is not defined

    - name: Register RHEL
      shell: subscription-manager register --username {{ username }} --password {{ password }} --auto-attach
      when:  ansible_distribution == "RedHat"

- name: Common Prerequisites
  block:
    - name: Install crictl
      unarchive:
        src: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.24.2/crictl-v1.24.2-linux-ppc64le.tar.gz"
        dest: "/usr/local/bin/"
        remote_src: yes

    - name: Add Public Docker repository
      yum_repository:
        name: public-docker
        description: Public Docker Repository
        baseurl: https://download.docker.com/linux/centos/8/ppc64le/stable/
        gpgcheck: no

    - name: Install iptables
      yum:
        name: iptables

- name: Install and Configure Runtime - Docker
  import_tasks: docker.yaml
  when: runtime == "docker"

- name: Install and Configure Runtime - Containerd
  import_tasks: containerd.yaml
  when: runtime == "containerd"
